package org.jbpm.demo.itorders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ApproverInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private java.lang.String seq;

	public ApproverInfo() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSeq() {
		return this.seq;
	}

	public void setSeq(java.lang.String seq) {
		this.seq = seq;
	}

	public ApproverInfo(java.lang.String name, java.lang.String seq) {
		this.name = name;
		this.seq = seq;
	}

}